spring.application.name=transaction
spring.datasource.url=jdbc:postgresql://localhost:5432/ledgerdb
spring.datasource.username=postgres
spring.datasource.password=yourpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.connection-timeout=30000

spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=null

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.topic = payment-events